Fix i18n, add clean working tree check (#1545)
* fix: i18n

* fix: connectors list

* feat: add clean git tree check

* fix: i18n files

* fix: i18n

diff --git a/.github/workflows/build-and-deploy-storybook.yml b/.github/workflows/build-and-deploy-storybook.yml
--- a/.github/workflows/build-and-deploy-storybook.yml
+++ b/.github/workflows/build-and-deploy-storybook.yml
@@ -10,6 +10,21 @@ on:
       - main
 
 jobs:
+  CheckCleanGitTree:
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+      - uses: pnpm/action-setup@v4
+      - run: pnpm deps
+      - run: pnpm build
+      - name: Check for uncommitted changes
+        run: |
+          # Show only the names of changed files
+          echo "Changed files:"
+          git diff --name-only HEAD --exit-code || (echo "Error: There are uncommitted changes in the working tree. Please commit or revert these changes." && exit 1)
+
   Lint:
     runs-on: ubuntu-22.04
     steps:
